version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      POSTGRES_PASSWORD: timescale
      POSTGRES_USER: timescale
      POSTGRES_DB: timescale
    ports:
      - 5432:5432

    
