version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: natrium
      POSTGRES_USER: natrium
      POSTGRES_DB: natrium
    ports:
      - 5432:5432
    
